<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Route;
use PanelKit\Panel\Http\Controllers\PanelAuthController;

/*
 * Sign-in for the client panel.
 *
 * GENERATED BY `make:panel client --auth` AND YOURS TO EDIT. The screens and the
 * controller ship in the package so they improve with it; this file is the
 * wiring, deliberately visible - a package that registered your sign-in routes
 * itself would be a package deciding how your customers get in.
 *
 * `defaults('panel', ...)` IS LOAD-BEARING. The controller reads it to know
 * which panel - and therefore which GUARD - a request belongs to. A panel
 * mounted at the root has no URL segment to infer it from, and one mounted at
 * `/admin/staff` has two, so the segment is not a usable answer.
 *
 * NOT NAMED `login`. Your application's own sign-in, if it has one, keeps that
 * name and that URI; this is `client.login` under `/client`.
 */
/*
 * `defaults('panel', ...)` GOES ON EACH ROUTE, not on the group.
 * `RouteRegistrar` has no `defaults()` - `Route::prefix(..)->defaults(..)`
 * throws BadMethodCallException at boot, which is how the first version of this
 * generator shipped and why `route:list` refused to run at all.
 */
Route::prefix('client')->group(function (): void {
    $panel = 'client';

    /*
     * NO `guest` MIDDLEWARE, deliberately. Laravel's redirects an
     * authenticated visitor to the application's HOME, which for a second
     * portal is somebody else's screen - so signing in to the admin panel and
     * then opening this one would bounce you somewhere unrelated with no
     * explanation. Showing the form to somebody already signed in costs
     * nothing.
     */
    Route::get('login', [PanelAuthController::class, 'showLogin'])
        ->defaults('panel', $panel)
        ->name('client.login');

    Route::post('login', [PanelAuthController::class, 'login'])
        ->defaults('panel', $panel)
        ->middleware('throttle:20,1');

    /*
     * LOGOUT IS BEHIND THE GUARD, so an unauthenticated POST is a redirect to
     * sign-in rather than a session teardown anybody can trigger.
     */
    Route::post('logout', [PanelAuthController::class, 'logout'])
        ->defaults('panel', $panel)
        ->middleware('auth:customers')
        ->name('client.logout');

    /*
     * THE RESET PAIR. Delete these four routes and set
     * `panel.auth.client.passwords` to false if this installation cannot send
     * mail - a "Forgot password?" link leading to a form that queues a message
     * nobody delivers is worse than no link, because somebody waits.
     */
    Route::get('forgot-password', [PanelAuthController::class, 'showForgotPassword'])
        ->defaults('panel', $panel)
        ->name('client.password.request');

    Route::post('forgot-password', [PanelAuthController::class, 'sendResetLink'])
        ->defaults('panel', $panel)
        ->middleware('throttle:6,1');

    Route::get('reset-password/{token}', [PanelAuthController::class, 'showResetPassword'])
        ->defaults('panel', $panel)
        ->name('client.password.reset');

    Route::post('reset-password', [PanelAuthController::class, 'resetPassword'])
        ->defaults('panel', $panel)
        ->middleware('throttle:6,1');
});
