<?php

declare(strict_types=1);

namespace App\Providers\Panels;

use Alxtexh\Panel\Panel;
use Alxtexh\Panel\PanelManager;
use Illuminate\Support\ServiceProvider;

/**
 * The admin panel.
 *
 * GENERATED BY `make:panel` AND MEANT TO BE EDITED. The interesting decisions
 * are all here in one place rather than spread across config: which guard
 * authenticates it, whether it is scoped to a tenant, what middleware it runs.
 *
 * TENANT CONTEXT: every query this panel makes is scoped to the resolved
 * organisation, and it refuses to operate without one. A null tenant key is
 * a DENY signal here, never "all tenants".
 *
 * ITS RESOURCES LIVE IN `app/Panel/Resources` and carry
 * `protected static string $panel = 'admin';`. Only those are routable under
 * `/` - a resource belonging to another panel is not reachable from here
 * at all, which is the point rather than a tidiness rule.
 *
 * ROUTES ARE REGISTERED FOR YOU, from `PanelRoutes`. There is no route file to
 * edit and no list to keep in step; a resource added to the directory above is
 * routable on the next request.
 */
final class AdminPanelProvider extends ServiceProvider
{
    public function boot(PanelManager $panels): void
    {
        $panels->registerPanel(
            Panel::make('admin')
                ->path('')
                /*
                 * THE GUARD IS NOT DECORATION. Everything in this panel resolves
                 * the acting user through it - never `$request->user()`, which
                 * reads the DEFAULT guard and returns null under a non-default
                 * one, failing open in ways that return 200 and look correct.
                 */
                ->guard('web')
                ->context(Panel::CONTEXT_TENANT)
                ->middleware(['web'])
                ->authMiddleware(['auth:web'])

                /*
                 * THIS PORTAL'S OWN SIGN-IN, at `//login`, named
                 * `admin.login` - which is the name the guest redirect looks
                 * for, so this one line is what stops a guest here being sent
                 * to the APPLICATION's front door and authenticated against
                 * the wrong guard.
                 */
                ->login()

                /*
                 * SELF-SERVICE RESET against Laravel's default `users` broker.
                 * The `web` guard's accounts live there on a stock install.
                 */
                ->passwordReset(true)
                ->passwordBroker('users')

                /*
                 * Opt-in page footer (v1.0.9). Off by default in the kit.
                 */
                ->pageFooter(true)

                /*
                 * WHAT THIS PORTAL DOES NOT MOUNT, AND WHY THE DEFAULT IS OFF.
                 *
                 * BACKUPS, LOGS AND MONITORING ARE THE INSTALLATION'S, not a
                 * portal's. They shipped ON by default, which is right for the
                 * one panel that IS the installation's admin and wrong for
                 * every other - and the cost of the wrong default was found
                 * here rather than reasoned about: the reference app's CUSTOMER
                 * portal mounted all three, so the people who BUY the service
                 * were one URL away from the log output. An ability gated them,
                 * but a route that exists is a route somebody can probe, and a
                 * permission is one grant away from being wrong.
                 *
                 * Delete a line to mount one deliberately. Opting in is a
                 * decision somebody made; opting out is a decision nobody
                 * knew they had to make.
                 */
                ->without([
                    'operations',
                    'assistant-settings',
                    'documents',
                    'trash',
                ])

                /*
                 * DISCOVERY BELONGS TO THE PANEL. It used to be an append to
                 * `config('panel.discover')` - a list every portal reads - so
                 * "add a portal" meant editing global state and which portal a
                 * resource landed in came from a property on the CLASS rather
                 * than from the panel that claims it. A portal that cannot
                 * state what it contains is not a separate portal.
                 */
                ->discoverResources(
                    in: app_path('Panel/Resources'),
                    for: 'App\\Panel\\Resources',
                )

                ->brandName(fn (): string => config('app.name')),
        );
    }
}
