<?php

declare(strict_types=1);

namespace PanelKit\Panel\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;
use PanelKit\Panel\Panel;
use PanelKit\Panel\PanelManager;

/**
 * Signing in to ONE panel, using that panel's own guard.
 *
 * WHY THIS IS NOT FORTIFY. Fortify is excellent and serves exactly one guard:
 * its routes are registered once, at the application root, against
 * `config('fortify.guard')`. A panel generated by `make:panel reseller` has its
 * OWN guard on its OWN path, and there is no second Fortify to give it. So
 * every generated portal meant hand-writing this file, and until somebody did,
 * the first panel page anybody opened died with `Route [login] not defined` -
 * an error that names nothing a newcomer can act on.
 *
 * IT DOES NOT REGISTER `/login`, EVER. The routes live under the panel's prefix
 * (`/reseller/login`), which is what lets this coexist with Breeze, Jetstream
 * or Fortify owning the application's root sign-in rather than fighting it for
 * the URI. A starter kit and a generated portal are then two doors into two
 * guards, which is the honest description of what they are.
 *
 * THE PANEL IS RESOLVED FROM THE ROUTE, not injected, because these actions are
 * mounted per panel by the generated routes file and Laravel gives a controller
 * no idea which group registered it. `panel()` reads the route default that
 * `--auth` writes; getting it wrong is a 404 rather than a wrong-guard sign-in,
 * because an unknown id resolves to null and every action aborts.
 */
final class PanelAuthController extends Controller
{
    public function showLogin(Request $request): Response
    {
        $panel = $this->panel($request);

        return Inertia::render('auth/Login', [
            'action' => $this->url($panel, 'login'),
            'forgotUrl' => $this->passwordsEnabled($panel)
                ? $this->url($panel, 'forgot-password')
                : null,
            'status' => $request->session()->get('status'),
            'heading' => config("panel.auth.{$panel->id}.heading"),
            'description' => config("panel.auth.{$panel->id}.description"),

            /*
             * THE DECISION IS MADE HERE, NOT IN THE COMPONENT, and it is the
             * only reason a prefill is acceptable at all. A Vue file cannot
             * know whether it is running in production; this can. Anything
             * other than `local` gets null, whatever config says.
             */
            'prefill' => app()->environment('local')
                ? config("panel.auth.{$panel->id}.prefill")
                : null,
        ]);
    }

    /**
     * THE THROTTLE IS THE POINT OF THIS METHOD, more than the credential check.
     *
     * Laravel's `Auth::attempt` will happily be called ten thousand times a
     * minute. The key is the address AND the ip together: keying on the address
     * alone lets anybody lock a colleague out of their own account by failing
     * to sign in as them, and keying on the ip alone lets one office share a
     * budget with an attacker behind the same NAT.
     *
     * THE MESSAGE IS THE SAME FOR A WRONG PASSWORD AND AN UNKNOWN ADDRESS.
     * Distinguishing them turns the form into an account-existence oracle.
     */
    public function login(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);

        $credentials = $request->validate([
            'email' => ['required', 'string', 'email'],
            'password' => ['required', 'string'],
        ]);

        $key = Str::transliterate(Str::lower($credentials['email']).'|'.$request->ip());
        $max = max(1, (int) config('panel.auth.max_attempts', 5));

        if (RateLimiter::tooManyAttempts($key, $max)) {
            throw ValidationException::withMessages([
                'email' => __('auth.throttle', [
                    'seconds' => $seconds = RateLimiter::availableIn($key),
                    'minutes' => (int) ceil($seconds / 60),
                ]),
            ]);
        }

        if (! Auth::guard($panel->getGuard())->attempt($credentials, $request->boolean('remember'))) {
            RateLimiter::hit($key, (int) config('panel.auth.decay_seconds', 60));

            throw ValidationException::withMessages([
                'email' => __('auth.failed'),
            ]);
        }

        RateLimiter::clear($key);

        /*
         * REGENERATED, WHICH IS NOT OPTIONAL. Without it the session id that
         * existed before sign-in still identifies the session after, so anyone
         * who planted one - a link with a session id, a shared machine - is
         * signed in as whoever used it. Session fixation is old and still the
         * easiest authentication bug to leave in.
         */
        $request->session()->regenerate();

        return redirect()->intended($this->panelHome($panel));
    }

    /**
     * INVALIDATE AND RE-TOKEN, not just `logout()`.
     *
     * `Auth::logout` forgets the user and leaves the session row intact, so
     * everything else written into it - a cart, a wizard's progress, a flash
     * message meant for somebody else - survives into the next person's visit
     * on a shared machine. Regenerating the CSRF token matters for the same
     * reason: the old one is still valid otherwise.
     */
    public function logout(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);

        Auth::guard($panel->getGuard())->logout();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect($this->url($panel, 'login'));
    }

    public function showForgotPassword(Request $request): Response
    {
        $panel = $this->panel($request);

        return Inertia::render('auth/ForgotPassword', [
            'action' => $this->url($panel, 'forgot-password'),
            'loginUrl' => $this->url($panel, 'login'),
            'status' => $request->session()->get('status'),
        ]);
    }

    /**
     * ONE ANSWER FOR A HIT AND A MISS, deliberately.
     *
     * Laravel's broker returns distinct statuses and it is tempting to render
     * them, because "we have no account with that address" is genuinely more
     * helpful. It is also an account-existence oracle: one address at a time,
     * anybody can learn who your customers are. The link is sent or it is not,
     * and the screen says the same thing either way.
     */
    public function sendResetLink(Request $request): RedirectResponse
    {
        $this->panel($request);

        $request->validate(['email' => ['required', 'string', 'email']]);

        Password::broker(config('panel.auth.broker'))->sendResetLink(
            $request->only('email'),
        );

        return back()->with(
            'status',
            __('If that address has an account, a reset link is on its way.'),
        );
    }

    public function showResetPassword(Request $request, string $token): Response
    {
        $panel = $this->panel($request);

        return Inertia::render('auth/ResetPassword', [
            'action' => $this->url($panel, 'reset-password'),
            'token' => $token,
            'email' => (string) $request->query('email', ''),
        ]);
    }

    public function resetPassword(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);

        $request->validate([
            'token' => ['required', 'string'],
            'email' => ['required', 'string', 'email'],
            'password' => ['required', 'string', 'confirmed', 'min:8'],
        ]);

        $status = Password::broker(config('panel.auth.broker'))->reset(
            $request->only('email', 'password', 'password_confirmation', 'token'),
            static function ($user, string $password): void {
                $user->forceFill(['password' => bcrypt($password)])->save();
            },
        );

        if ($status !== Password::PASSWORD_RESET) {
            throw ValidationException::withMessages(['email' => __($status)]);
        }

        return redirect($this->url($panel, 'login'))->with('status', __($status));
    }

    /* ------------------------------------------------------------- helpers */

    /**
     * WHICH PANEL THIS REQUEST BELONGS TO.
     *
     * From a route default rather than a segment: a panel mounted at the root
     * has no segment to read, and one mounted at `/admin/staff` has two.
     * `--auth` writes `->defaults('panel', $id)` on the group.
     */
    private function panel(Request $request): Panel
    {
        $id = (string) $request->route()?->defaults['panel'];

        $panel = app(PanelManager::class)->panel($id);

        abort_if($panel === null, 404);

        return $panel;
    }

    /** A URL inside the panel's own prefix. */
    private function url(Panel $panel, string $path): string
    {
        return '/'.trim(trim($panel->getPath(), '/').'/'.$path, '/');
    }

    /**
     * Where a signed-in person lands.
     *
     * The panel's root, which `PanelRoutes` answers with the home screen or the
     * dashboard depending on what the installation registered. Deliberately not
     * a named route: a generated portal's route names belong to the application.
     */
    private function panelHome(Panel $panel): string
    {
        return '/'.trim($panel->getPath(), '/');
    }

    /**
     * Whether the reset pair was routed.
     *
     * OFF UNLESS THE APPLICATION CAN SEND MAIL, which `--auth` asks about,
     * because a "Forgot password?" link that leads to a form that silently
     * queues a mail nobody delivers is worse than no link: somebody waits.
     */
    private function passwordsEnabled(Panel $panel): bool
    {
        return (bool) config("panel.auth.{$panel->id}.passwords", true);
    }
}
