<?php

declare(strict_types=1);

namespace App\Providers\Panels;

use Illuminate\Support\ServiceProvider;
use PanelKit\Panel\Panel;
use PanelKit\Panel\PanelManager;

/**
 * The client panel.
 *
 * GENERATED BY `make:panel` AND MEANT TO BE EDITED. The interesting decisions
 * are all here in one place rather than spread across config: which guard
 * authenticates it, whether it is scoped to a tenant, what middleware it runs.
 *
 * TENANT CONTEXT: every query this panel makes is scoped to the resolved
 * organisation, and it refuses to operate without one. A null tenant key is
 * a DENY signal here, never "all tenants".
 *
 * ITS RESOURCES LIVE IN `app/Panel/Client/Resources` and carry
 * `protected static string $panel = 'client';`. Only those are routable under
 * `/client` - a resource belonging to another panel is not reachable from here
 * at all, which is the point rather than a tidiness rule.
 *
 * ROUTES ARE REGISTERED FOR YOU, from `PanelRoutes`. There is no route file to
 * edit and no list to keep in step; a resource added to the directory above is
 * routable on the next request.
 */
final class ClientPanelProvider extends ServiceProvider
{
    public function boot(PanelManager $panels): void
    {
        $panels->registerPanel(
            Panel::make('client')
                ->path('client')
                /*
                 * THE GUARD IS NOT DECORATION. Everything in this panel resolves
                 * the acting user through it - never `$request->user()`, which
                 * reads the DEFAULT guard and returns null under a non-default
                 * one, failing open in ways that return 200 and look correct.
                 */
                ->guard('customers')
                ->context(Panel::CONTEXT_TENANT)
                ->middleware(['web'])
                ->authMiddleware(['auth:customers'])
                ->brandName(fn (): string => config('app.name').' — Client'),
        );

        /*
         * DISCOVERY IS DECLARED HERE, beside the panel it belongs to, rather
         * than in a shared config list. A panel whose resource directory is not
         * discovered has no resources, no routes and an empty menu - and nothing
         * fails, which is the worst way for a configuration step to be missed.
         */
        config([
            'panel.discover' => [
                ...(array) config('panel.discover', []),
                app_path('Panel/Client/Resources') => 'App\\Panel\\Client\\Resources',
            ],
        ]);
    }
}
