<?php

declare(strict_types=1);

namespace App\Providers\Panels;

use App\Models\Plan;
use Illuminate\Support\ServiceProvider;
use Alxtexh\Panel\Panel;
use Alxtexh\Panel\PanelManager;

/**
 * The client panel.
 *
 * GENERATED BY `make:panel` AND MEANT TO BE EDITED. The interesting decisions
 * are all here in one place rather than spread across config: which guard
 * authenticates it, whether it is scoped to a tenant, what middleware it runs.
 *
 * TENANT CONTEXT: every query this panel makes is scoped to the resolved
 * organisation, and it refuses to operate without one. A null tenant key is
 * a DENY signal here, never "all tenants".
 *
 * ITS RESOURCES LIVE IN `app/Panel/Client/Resources` and carry
 * `protected static string $panel = 'client';`. Only those are routable under
 * `/client` - a resource belonging to another panel is not reachable from here
 * at all, which is the point rather than a tidiness rule.
 *
 * ROUTES ARE REGISTERED FOR YOU, from `PanelRoutes`. There is no route file to
 * edit and no list to keep in step; a resource added to the directory above is
 * routable on the next request.
 */
final class ClientPanelProvider extends ServiceProvider
{
    public function boot(PanelManager $panels): void
    {
        $panels->registerPanel(
            Panel::make('client')
                ->path('client')
                /*
                 * THE GUARD IS NOT DECORATION. Everything in this panel resolves
                 * the acting user through it - never `$request->user()`, which
                 * reads the DEFAULT guard and returns null under a non-default
                 * one, failing open in ways that return 200 and look correct.
                 */
                ->guard('customers')
                ->context(Panel::CONTEXT_TENANT)
                ->middleware(['web'])
                ->authMiddleware(['auth:customers'])

                /*
                 * ITS OWN SIGN-IN, mounted at `/client/login`. The routes used
                 * to come from a generated `routes/panel-client-auth.php`; the
                 * panel declares them now, and the generated file remains
                 * supported for a portal that needs a sign-in the packaged
                 * controller does not do.
                 */
                ->login()

                /*
                 * ITS OWN BROKER, AND IT WAS WRONG BEFORE. `panel.auth.broker`
                 * is `users` - the OPERATOR provider - so a customer asking
                 * this portal for a reset had their address looked up among
                 * operators, and an address held by both would have mailed a
                 * working reset link for the operator account. See
                 * `Panel::passwordBroker()`.
                 */
                ->passwordBroker('customers')

                /*
                 * WHAT A CUSTOMER PORTAL MUST NOT MOUNT.
                 *
                 * THESE WERE ALL REACHABLE AND NOBODY KNEW, which is worth
                 * spelling out. The guest redirect was broken (see
                 * `PanelServiceProvider::redirectGuestsToTheirPanel`), so the
                 * screen crawler could never sign in to this portal and every
                 * one of these went uncrawled. The moment it could, it found
                 * BACKUPS, LOGS and MONITORING mounted on the portal for the
                 * people who BUY the service - a customer one URL away from
                 * the installation's log output.
                 *
                 * Two bugs hid each other: a portal that offered too much, and
                 * a test that could not reach it to say so.
                 */
                ->without([
                    'operations',
                    'assistant-settings',
                    'trash',
                    'documents',
                ])

                ->brandName(fn (): string => config('app.name').' - Client')

                /*
                 | THE WORKED EXAMPLE FOR `authFamily('showcase')` (login-02 /
                 | signup-02 / otp-02) - form on the left, a preview panel and
                 | a testimonial on the right. A subscriber portal is the
                 | natural home for the pitch a showcase panel makes: unlike
                 | the operator portal, somebody landing here has not
                 | necessarily decided to sign up yet.
                 |
                 | THE QUOTE IS PLACEHOLDER COPY, the same way every other
                 | figure in this demo is - nobody named here exists, the same
                 | as no ISP at "RTR-01-001" does.
                 */
                ->authFamily('showcase')
                ->authTestimonial(
                    'Switching subscribers between plans used to mean a support ticket and a wait. Now it is a click, and the audit trail writes itself.',
                    'Amara Odhiambo',
                    'Head of Operations',
                )

                /*
                 * `PlanCatalogPage`, at `/client/account/subscription` -
                 * "choose a plan", not the read-only comparison table
                 * `Client\Resources\PlanResource` already offers.
                 *
                 * THIS CLOSURE IS A SHOWCASE, LIKE `PaymentGatewaySettings` -
                 * no live processor is wired into the demo, and it does not
                 * write anything: no `Customer` field records "the plan
                 * somebody chose", on purpose (see `PlanCatalogPage`'s own
                 * docblock - not every business that sells packages has a
                 * single exclusive "current" one to update). It sends the
                 * browser to a DEDICATED CONFIRMATION PAGE this app owns
                 * (`SubscriptionConfirmedPage`) rather than an external
                 * checkout - the other of the two endings
                 * `PlanCatalogPage::checkout()`'s docblock describes. A host
                 * with a real processor replaces this closure with one that
                 * creates a Stripe/Paddle/etc checkout session and returns
                 * ITS url instead.
                 */
                ->planCatalog(function (Panel $panel, mixed $user, mixed $request, string $planId): string {
                    $plan = Plan::query()->find($planId);

                    $prefix = trim((string) $panel->getPath(), '/');
                    $query = $plan !== null ? '?plan='.$plan->getKey() : '';

                    return ($prefix !== '' ? '/'.$prefix : '').'/subscription-confirmed'.$query;
                })

                /*
                 * DISCOVERY BELONGS TO THE PANEL, not to a shared config list.
                 * It used to append to `panel.discover`, which every portal
                 * reads - so adding a portal meant editing global state and a
                 * resource's home came from a property on the class rather
                 * than from the panel claiming it.
                 */
                ->discoverResources(
                    in: app_path('Panel/Client/Resources'),
                    for: 'App\\Panel\\Client\\Resources',
                ),
        );
    }
}
