<?php

declare(strict_types=1);

namespace App\Providers\Panels;

use Illuminate\Support\ServiceProvider;
use PanelKit\Panel\Panel;
use PanelKit\Panel\PanelManager;

/**
 * The platform panel.
 *
 * GENERATED BY `make:panel` AND MEANT TO BE EDITED. The interesting decisions
 * are all here in one place rather than spread across config: which guard
 * authenticates it, whether it is scoped to a tenant, what middleware it runs.
 *
 * CENTRAL CONTEXT: no tenant scoping is applied to anything this panel
 * queries. That is what a platform portal needs and what a tenant portal
 * must never have - a central query reached from a tenant request is the
 * leak the panel split exists to prevent.
 *
 * ITS RESOURCES LIVE IN `app/Panel/Platform/Resources` and carry
 * `protected static string $panel = 'platform';`. Only those are routable under
 * `/platform` - a resource belonging to another panel is not reachable from here
 * at all, which is the point rather than a tidiness rule.
 *
 * ROUTES ARE REGISTERED FOR YOU, from `PanelRoutes`. There is no route file to
 * edit and no list to keep in step; a resource added to the directory above is
 * routable on the next request.
 */
final class PlatformPanelProvider extends ServiceProvider
{
    public function boot(PanelManager $panels): void
    {
        $panels->registerPanel(
            Panel::make('platform')
                ->path('platform')
                /*
                 * THE GUARD IS NOT DECORATION. Everything in this panel resolves
                 * the acting user through it - never `$request->user()`, which
                 * reads the DEFAULT guard and returns null under a non-default
                 * one, failing open in ways that return 200 and look correct.
                 */
                ->guard('web')
                ->context(Panel::CONTEXT_CENTRAL)
                ->middleware(['web'])
                ->authMiddleware(['auth:web'])
                ->brandName(fn (): string => config('app.name').' — Platform')
                /*
                 * NO OPERATIONS SCREENS IN THIS PORTAL.
                 *
                 * They ship with the package now and are offered by default,
                 * which is right for a panel that IS the installation's admin.
                 * This one is not: backups, logs and host metrics belong to
                 * whoever runs the installation, and routing them here would
                 * put a restore button behind a guard that should never reach
                 * one - protected by an ability nobody in this portal holds,
                 * but a route that exists is a route somebody can probe.
                 */
                ->without(['operations']),
        );

        /*
         * DISCOVERY IS DECLARED HERE, beside the panel it belongs to, rather
         * than in a shared config list. A panel whose resource directory is not
         * discovered has no resources, no routes and an empty menu - and nothing
         * fails, which is the worst way for a configuration step to be missed.
         */
        config([
            'panel.discover' => [
                ...(array) config('panel.discover', []),
                app_path('Panel/Platform/Resources') => 'App\\Panel\\Platform\\Resources',
            ],
        ]);
    }
}
