<?php

declare(strict_types=1);

namespace App\Providers\Panels;

use Illuminate\Support\ServiceProvider;
use Alxtexh\Panel\Panel;
use Alxtexh\Panel\PanelManager;

/**
 * The platform panel.
 *
 * GENERATED BY `make:panel` AND MEANT TO BE EDITED. The interesting decisions
 * are all here in one place rather than spread across config: which guard
 * authenticates it, whether it is scoped to a tenant, what middleware it runs.
 *
 * CENTRAL CONTEXT: no tenant scoping is applied to anything this panel
 * queries. That is what a platform portal needs and what a tenant portal
 * must never have - a central query reached from a tenant request is the
 * leak the panel split exists to prevent.
 *
 * ITS RESOURCES LIVE IN `app/Panel/Platform/Resources` and carry
 * `protected static string $panel = 'platform';`. Only those are routable under
 * `/platform` - a resource belonging to another panel is not reachable from here
 * at all, which is the point rather than a tidiness rule.
 *
 * ROUTES ARE REGISTERED FOR YOU, from `PanelRoutes`. There is no route file to
 * edit and no list to keep in step; a resource added to the directory above is
 * routable on the next request.
 */
final class PlatformPanelProvider extends ServiceProvider
{
    public function boot(PanelManager $panels): void
    {
        $panels->registerPanel(
            Panel::make('platform')
                ->path('platform')
                /*
                 * THE GUARD IS NOT DECORATION. Everything in this panel resolves
                 * the acting user through it - never `$request->user()`, which
                 * reads the DEFAULT guard and returns null under a non-default
                 * one, failing open in ways that return 200 and look correct.
                 */
                ->guard('web')
                ->context(Panel::CONTEXT_CENTRAL)
                ->middleware(['web'])
                ->authMiddleware(['auth:web'])
                ->brandName(fn (): string => config('app.name').' — Platform')
                /*
                 * NO OPERATIONS SCREENS IN THIS PORTAL, AND NOTHING TO WRITE
                 * TO GET THAT: `Panel::offers()` treats operations and
                 * assistant settings as off unless asked for. Backups, logs
                 * and host metrics belong to whoever runs the installation,
                 * not to a panel that manages tenants - routing them here
                 * would put a restore button behind a guard nobody in this
                 * portal holds, and a route that exists is a route somebody
                 * can probe regardless of the ability gating it.
                 *
                 * DOCUMENTS AND TRASH ARE ASKED FOR: this portal manages the
                 * document templates every tenant's invoices render from, and
                 * a bin for records it deletes.
                 */
                ->with(['documents', 'trash'])

                /*
                 * DISCOVERY BELONGS TO THE PANEL, not to a shared config list.
                 * It used to append to `panel.discover`, which every portal
                 * reads - so adding a portal meant editing global state, and
                 * which portal a resource landed in came from a property on
                 * the CLASS rather than from the panel that claims it. A
                 * portal that cannot state what it contains is not a separate
                 * portal.
                 */
                ->discoverResources(
                    in: app_path('Panel/Platform/Resources'),
                    for: 'App\Panel\Platform\Resources',
                ),
        );
    }
}
