<?php

declare(strict_types=1);

namespace App\Providers\Panels;

use Illuminate\Support\ServiceProvider;
use Alxtexh\Panel\Panel;
use Alxtexh\Panel\PanelManager;

/**
 * The reseller panel.
 *
 * GENERATED BY `make:panel` AND MEANT TO BE EDITED. The interesting decisions
 * are all here in one place rather than spread across config: which guard
 * authenticates it, whether it is scoped to a tenant, what middleware it runs.
 *
 * TENANT CONTEXT: every query this panel makes is scoped to the resolved
 * organisation, and it refuses to operate without one. A null tenant key is
 * a DENY signal here, never "all tenants".
 *
 * ITS RESOURCES LIVE IN `app/Panel/Reseller/Resources` and carry
 * `protected static string $panel = 'reseller';`. Only those are routable under
 * `/reseller` - a resource belonging to another panel is not reachable from here
 * at all, which is the point rather than a tidiness rule.
 *
 * ROUTES ARE REGISTERED FOR YOU, from `PanelRoutes`. There is no route file to
 * edit and no list to keep in step; a resource added to the directory above is
 * routable on the next request.
 */
final class ResellerPanelProvider extends ServiceProvider
{
    public function boot(PanelManager $panels): void
    {
        $panels->registerPanel(
            Panel::make('reseller')
                ->path('reseller')
                /*
                 * THE GUARD IS NOT DECORATION. Everything in this panel resolves
                 * the acting user through it - never `$request->user()`, which
                 * reads the DEFAULT guard and returns null under a non-default
                 * one, failing open in ways that return 200 and look correct.
                 */
                ->guard('web')
                ->context(Panel::CONTEXT_TENANT)
                ->middleware(['web'])
                ->authMiddleware(['auth:web'])
                ->brandName(fn (): string => config('app.name').' - Reseller')
                /*
                 | WORKED EXAMPLE FOR `authFamily('card')` (login-04 / signup-04 /
                 | otp-04): muted page with an inset form|image card. Couples
                 | login, register, and OTP together. Admin stays on the default
                 | centered family; client uses showcase.
                 */
                ->authFamily('card')
                /*
                 * NO OPERATIONS SCREENS IN THIS PORTAL.
                 *
                 * They ship with the package now and are offered by default,
                 * which is right for a panel that IS the installation's admin.
                 * This one is not: backups, logs and host metrics belong to
                 * whoever runs the installation, and routing them here would
                 * put a restore button behind a guard that should never reach
                 * one - protected by an ability nobody in this portal holds,
                 * but a route that exists is a route somebody can probe.
                 */
                ->without(['operations', 'assistant-settings'])

                /*
                 * DISCOVERY BELONGS TO THE PANEL, not to a shared config list.
                 * It used to append to `panel.discover`, which every portal
                 * reads - so adding a portal meant editing global state, and
                 * which portal a resource landed in came from a property on
                 * the CLASS rather than from the panel that claims it. A
                 * portal that cannot state what it contains is not a separate
                 * portal.
                 */
                ->discoverResources(
                    in: app_path('Panel/Reseller/Resources'),
                    for: 'App\Panel\Reseller\Resources',
                ),
        );
    }
}
