<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\Tenant;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Schema;
use PanelKit\Panel\PanelManager;
use PanelKit\Panel\Resources\Resource;
use PanelKit\Panel\Support\TenantContext;
use Tests\TestCase;

/**
 * Nothing crosses the [client] portal's boundary - generated by make:panel.
 *
 * This portal is TENANT-SCOPED: every query it makes is constrained to the
 * organisation the request resolved, and a null tenant denies rather than
 * matching everything.
 *
 * WHY THIS FILE IS GENERATED WITH THE PORTAL. Multi-panel scoping is the
 * structural claim this panel makes, and a claim proved by a test somebody
 * has to go and find is a claim that quietly stops being true. Adding a
 * portal adds its own evidence.
 *
 * IT ENUMERATES THE REGISTRY rather than naming resources, so a resource
 * added to this portal tomorrow is covered without this file changing. If
 * it ever grows a hand-written list it has stopped doing its job.
 *
 * EDIT IT FREELY - it is a starting point, not a contract. What should not
 * change is the enumeration.
 */
final class ClientPanelIsolationTest extends TestCase
{
    use RefreshDatabase;

    private const PANEL = 'client';

    /**
     * EVERY RESOURCE HERE IS TENANT-OWNED, derived from the TABLE rather
     * than from a name list.
     *
     * A resource that is genuinely tenant-owned HAS the column, so the day
     * somebody adds one to this portal that is not scoped, this fails. An
     * exclusion keyed on a resource's NAME would let it through silently,
     * which is the direction that matters.
     */
    public function test_every_resource_in_this_portal_is_tenant_scoped(): void
    {
        $column = app(TenantContext::class)->column();

        $unscoped = [];

        foreach ($this->resources() as $key => $class) {
            $table = (new ($class::model()))->getTable();

            if (! Schema::hasColumn($table, $column)) {
                $unscoped[] = "[{$key}] is served by a tenant portal and its table "
                    ."[{$table}] has no [{$column}] column.";
            }
        }

        $this->assertSame([], $unscoped, '
'.implode('
', $unscoped).'
');
    }

    /**
     * AND EVERY ONE HAS A POLICY. The panel denies every ability when none
     * is registered - the safe default, and one that looks exactly like a
     * permissions bug from the operator's side.
     */
    public function test_every_resource_in_this_portal_has_a_policy(): void
    {
        $missing = [];

        foreach ($this->resources() as $key => $class) {
            if (Gate::getPolicyFor($class::model()) === null) {
                $missing[] = "[{$key}] has no policy, so nobody can open it.";
            }
        }

        $this->assertSame([], $missing, '
'.implode('
', $missing).'
');
    }

    /**
     * A NULL TENANT DENIES, rather than matching everything. This is the
     * assertion that would catch a scope quietly removed: without a
     * resolved organisation the portal must refuse, never serve the union.
     */
    public function test_the_portal_refuses_a_request_with_no_tenant(): void
    {
        $tenant = Tenant::create(['name' => 'Acme', 'slug' => 'acme']);

        $user = User::factory()->create([
            'tenant_id' => $tenant->id,
            'email_verified_at' => now(),
        ]);

        config(['panel.tenancy.resolver' => fn () => null]);

        foreach (array_keys($this->resources()) as $key) {
            $response = $this->actingAs($user)->get('/client/'.$key);

            $this->assertContains(
                $response->status(),
                [403, 404, 302],
                "[{$key}] served a request with no organisation resolved.",
            );
        }
    }

    /** And another portal's resource is not reachable under this one's path. */
    public function test_another_portals_resource_is_not_mounted_here(): void
    {
        $manager = app(PanelManager::class);

        $mine = array_keys($this->resources());

        $foreign = array_diff(array_keys($manager->resources()), $mine);

        if ($foreign === []) {
            $this->markTestSkipped('This installation has only one portal.');
        }

        $tenant = Tenant::create(['name' => 'Acme', 'slug' => 'acme']);

        $user = User::factory()->create([
            'tenant_id' => $tenant->id,
            'email_verified_at' => now(),
        ]);

        config(['panel.tenancy.resolver' => fn () => $tenant->id]);

        foreach ($foreign as $key) {
            $this->actingAs($user)
                ->get('/client/'.$key)
                ->assertNotFound();
        }
    }

    /**
     * The resources this portal serves, and only this portal's.
     *
     * @return array<string, class-string<\PanelKit\Panel\Resources\Resource>>
     */
    private function resources(): array
    {
        return app(PanelManager::class)->resourcesFor(self::PANEL);
    }
}
