#!/usr/bin/env bash
#
# Install PanelKit into a FRESH Laravel application and prove it boots.
#
# WHY THIS EXISTS. Every test in this repository runs inside the monorepo, where
# the playground reaches the package through a `path` repository and a symlink.
# That arrangement hides the entire class of faults that only appear when
# somebody installs the package for real: a class outside the published autoload
# paths, a service provider that is never discovered because `extra.laravel` is
# wrong, a config the application never receives because the publish tag is
# misspelt, a `require` on a dev-only dependency. None of those fail a single
# one of the 1,492 tests, and all of them fail the first person who runs
# `composer require panelkit/panel`.
#
# The README has told people to run that command since the beginning. Nothing
# ever checked that it works.
#
# WHAT IT DOES, in the order the README claims:
#
#   composer require panelkit/panel
#   npm install @panelkit/ui @panelkit/inertia
#   php artisan panel:install
#   php artisan make:panel-resource ... --generate
#
# and then asserts the resource's route exists - because "it installed" and "it
# works" are different claims, and only the second one is worth making.
#
# HOW IT RESOLVES THE PACKAGE. Nothing is published yet, so this points composer
# at a `git subtree split` branch of THIS repository as a vcs source. That is
# deliberately not a path symlink: a vcs install exercises composer's real
# resolution, its autoload generation and Laravel's package discovery, which is
# the whole point. The npm side installs from `npm pack` tarballs for the same
# reason - a tarball contains exactly the files `files` in package.json allows,
# so a component left out of that list fails here rather than at a consumer.
#
# Usage:
#   scripts/verify-install.sh            # build, install, assert, clean up
#   scripts/verify-install.sh --keep     # leave the scratch app for inspection

set -euo pipefail

KEEP=false
[[ "${1:-}" == "--keep" ]] && KEEP=true

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
APP="$WORK/fresh-app"

cleanup() {
    if [[ "$KEEP" == true ]]; then
        echo "==> Left in place: $WORK"
    else
        rm -rf "$WORK"
    fi
}
trap cleanup EXIT

say() { echo "==> $*"; }
fail() { echo "FAIL: $*" >&2; exit 1; }

cd "$ROOT"

# A subtree split reads COMMITTED history. Splitting a dirty tree silently
# produces a package without the uncommitted work, which looks like the split
# dropped it.
if [[ -n "$(git status --porcelain)" ]]; then
    fail "Working tree is not clean - a split reads history, so changes would be silently omitted."
fi

# ---------------------------------------------------------------- the package

say "Splitting packages/panel into a standalone branch"
git branch -D verify/panel >/dev/null 2>&1 || true
git subtree split --prefix=packages/panel -b verify/panel >/dev/null

say "Creating a fresh Laravel application"
composer create-project laravel/laravel "$APP" \
    --no-interaction --prefer-dist --quiet 2>&1 | tail -3

cd "$APP"

say "composer require panelkit/panel"
composer config minimum-stability dev --no-interaction
composer config prefer-stable true --no-interaction
composer config repositories.panelkit "{\"type\":\"vcs\",\"url\":\"$ROOT\"}" --json --no-interaction
composer require panelkit/panel:dev-verify/panel --no-interaction --quiet 2>&1 | tail -5

# THE FIRST REAL ASSERTION. If `extra.laravel.providers` is wrong, or the
# autoload paths do not cover the command, the package installs perfectly and
# contributes nothing - which is exactly the failure a symlinked monorepo hides.
say "Checking Laravel discovered the package"
php artisan list --no-ansi 2>/dev/null | grep -q 'panel:install' \
    || fail "panel:install is not registered - the service provider was not discovered."

# ------------------------------------------------------------- the client half

say "Packing and installing the npm packages"
for pkg in ui inertia; do
    tarball="$(cd "$ROOT/packages/$pkg" && npm pack --silent --pack-destination "$WORK")"
    [[ -f "$WORK/$tarball" ]] || fail "npm pack produced nothing for packages/$pkg"
    npm install --silent --no-audit --no-fund "$WORK/$tarball" 2>&1 | tail -2
done

# ------------------------------------------------------------------ the install

say "php artisan panel:install"
php artisan panel:install --no-interaction 2>&1 | tail -5

# THE MODEL COMES FIRST, because a resource is generated by reading its table.
# The README omitted this, so following it exactly failed here - which is the
# first thing this harness found and the reason it exists.
say "Creating a model and its table"
php artisan make:model Customer -m --no-interaction 2>&1 | tail -2
migration="$(ls -1 database/migrations/*_create_customers_table.php | head -1)"
python3 - "$migration" <<'EOF'
import sys, re
p = sys.argv[1]
s = open(p).read()
s = s.replace("$table->id();", "$table->id();\n            $table->string('name');\n            $table->string('email')->nullable();", 1)
open(p, 'w').write(s)
EOF
php artisan migrate --force --no-interaction 2>&1 | tail -2

say "Generating a resource"
php artisan make:panel-resource Customer --generate --no-interaction 2>&1 | tail -5

# THE PERMISSION SYSTEM IS THE PACKAGE'S NOW, so a fresh install must arrive with
# one that works rather than with instructions for building one. This is the only
# place that can prove it: inside the monorepo the reference app's own migration
# chain built these tables long before the package owned them, so every test in
# the suite runs against a schema the package migration merely declines to touch.
#
# `sync` is the honest assertion - it derives ability names from the generated
# resource, creates the permission rows, and creates an Administrator role holding
# them. If the migration did not run, or `grants_all` is missing, or the model is
# not autoloaded, this is where it surfaces.
say "php artisan panel:permissions sync"
php artisan panel:permissions sync --no-interaction 2>&1 | tail -5

php artisan tinker --execute="
    exit(
        Schema::hasColumn('roles', 'grants_all')
        && PanelKit\Panel\Models\Role::query()->where('grants_all', true)->exists()
        && Spatie\Permission\Models\Permission::query()->where('name', 'view_any_customers')->exists()
            ? 0 : 1
    );
" 2>/dev/null || fail "panel:permissions ran but left no working role - the shipped permission system does not work on a clean install."

say "Permissions reconciled: an Administrator role holds the generated resource's abilities"

# A PANEL NEEDS AN APPLICATION THAT CAN AUTHENTICATE. `laravel/laravel` ships
# no auth scaffolding, so there is no `login` route for the guard to send an
# anonymous visitor to - and the first visit dies with "Route [login] not
# defined", which names nothing a newcomer can act on. A real installation has
# Fortify, Breeze or a starter kit; this stands in for one.
say "Adding a login route (standing in for auth scaffolding)"
cat >> routes/web.php <<'ROUTE'

Route::get('/login', fn () => 'login')->name('login');
ROUTE

# THE ASSERTION WORTH MAKING, and it is not a grep of route:list. Panel routes
# use a `{resource}` placeholder constrained by `whereIn`, so no route URI ever
# contains the literal "customers" - an earlier version of this script asserted
# exactly that and reported a bug that did not exist. Resolving the URL is the
# only honest check: 404 means unrouted, 500 means broken, a redirect to login
# means the route matched and the guard ran.
say "Checking the resource URL resolves"
cat > verify-hit.php <<'HIT'
<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
$status = $kernel->handle(Illuminate\Http\Request::create('/customers', 'GET'))->getStatusCode();
echo $status, PHP_EOL;
HIT
status="$(php verify-hit.php 2>/dev/null | tail -1)"
rm -f verify-hit.php

case "$status" in
    404) fail "/customers is not routed - discovery or panel mounting did not happen." ;;
    5*)  fail "/customers is routed but returns $status - the panel errors on a clean install." ;;
    "")  fail "/customers could not be requested at all." ;;
esac

say "/customers resolved with HTTP $status"

echo
echo "PASS - panelkit/panel installs into a fresh Laravel app, is discovered,"
echo "       installs its pages, generates a resource and routes it."
