#!/usr/bin/env bash
#
# Install PanelKit into a FRESH Laravel application and prove it boots.
#
# WHY THIS EXISTS. Every test in this repository runs inside the monorepo, where
# the playground reaches the package through a `path` repository and a symlink.
# That arrangement hides the entire class of faults that only appear when
# somebody installs the package for real: a class outside the published autoload
# paths, a service provider that is never discovered because `extra.laravel` is
# wrong, a config the application never receives because the publish tag is
# misspelt, a `require` on a dev-only dependency. None of those fail a single
# one of the 1,492 tests, and all of them fail the first person who runs
# `composer require panelkit/panel`.
#
# The README has told people to run that command since the beginning. Nothing
# ever checked that it works.
#
# WHAT IT DOES, in the order the README claims:
#
#   composer require panelkit/panel
#   npm install @panelkit/ui @panelkit/inertia
#   php artisan panel:install
#   php artisan make:panel-resource ... --generate
#
# and then asserts the resource's route exists - because "it installed" and "it
# works" are different claims, and only the second one is worth making.
#
# HOW IT RESOLVES THE PACKAGE. Nothing is published yet, so this points composer
# at a `git subtree split` branch of THIS repository as a vcs source. That is
# deliberately not a path symlink: a vcs install exercises composer's real
# resolution, its autoload generation and Laravel's package discovery, which is
# the whole point. The npm side installs from `npm pack` tarballs for the same
# reason - a tarball contains exactly the files `files` in package.json allows,
# so a component left out of that list fails here rather than at a consumer.
#
# Usage:
#   scripts/verify-install.sh            # build, install, assert, clean up
#   scripts/verify-install.sh --keep     # leave the scratch app for inspection

set -euo pipefail

KEEP=false
[[ "${1:-}" == "--keep" ]] && KEEP=true

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
APP="$WORK/fresh-app"

cleanup() {
    if [[ "$KEEP" == true ]]; then
        echo "==> Left in place: $WORK"
    else
        rm -rf "$WORK"
    fi
}
trap cleanup EXIT

say() { echo "==> $*"; }
fail() { echo "FAIL: $*" >&2; exit 1; }

cd "$ROOT"

# A subtree split reads COMMITTED history. Splitting a dirty tree silently
# produces a package without the uncommitted work, which looks like the split
# dropped it.
if [[ -n "$(git status --porcelain)" ]]; then
    fail "Working tree is not clean - a split reads history, so changes would be silently omitted."
fi

# ---------------------------------------------------------------- the package

say "Splitting packages/panel into a standalone branch"
git branch -D verify/panel >/dev/null 2>&1 || true
git subtree split --prefix=packages/panel -b verify/panel >/dev/null

say "Creating a fresh Laravel application"
composer create-project laravel/laravel "$APP" \
    --no-interaction --prefer-dist --quiet 2>&1 | tail -3

cd "$APP"

say "composer require panelkit/panel"
composer config minimum-stability dev --no-interaction
composer config prefer-stable true --no-interaction
composer config repositories.panelkit "{\"type\":\"vcs\",\"url\":\"$ROOT\"}" --json --no-interaction
composer require panelkit/panel:dev-verify/panel --no-interaction --quiet 2>&1 | tail -5

# THE FIRST REAL ASSERTION. If `extra.laravel.providers` is wrong, or the
# autoload paths do not cover the command, the package installs perfectly and
# contributes nothing - which is exactly the failure a symlinked monorepo hides.
say "Checking Laravel discovered the package"
php artisan list --no-ansi 2>/dev/null | grep -q 'panel:install' \
    || fail "panel:install is not registered - the service provider was not discovered."

# ------------------------------------------------------------- the client half

say "Packing and installing the npm packages"
for pkg in ui inertia; do
    tarball="$(cd "$ROOT/packages/$pkg" && npm pack --silent --pack-destination "$WORK")"
    [[ -f "$WORK/$tarball" ]] || fail "npm pack produced nothing for packages/$pkg"
    npm install --silent --no-audit --no-fund "$WORK/$tarball" 2>&1 | tail -2
done

# ------------------------------------------------------------------ the install

say "php artisan panel:install"
php artisan panel:install --no-interaction 2>&1 | tail -5

# THE MODEL COMES FIRST, because a resource is generated by reading its table.
# The README omitted this, so following it exactly failed here - which is the
# first thing this harness found and the reason it exists.
say "Creating a model and its table"
php artisan make:model Customer -m --no-interaction 2>&1 | tail -2
migration="$(ls -1 database/migrations/*_create_customers_table.php | head -1)"
python3 - "$migration" <<'EOF'
import sys, re
p = sys.argv[1]
s = open(p).read()
s = s.replace("$table->id();", "$table->id();\n            $table->string('name');\n            $table->string('email')->nullable();", 1)
open(p, 'w').write(s)
EOF
php artisan migrate --force --no-interaction 2>&1 | tail -2

say "Generating a resource"
php artisan make:panel-resource Customer --generate --no-interaction 2>&1 | tail -5

# THE PERMISSION SYSTEM IS THE PACKAGE'S NOW, so a fresh install must arrive with
# one that works rather than with instructions for building one. This is the only
# place that can prove it: inside the monorepo the reference app's own migration
# chain built these tables long before the package owned them, so every test in
# the suite runs against a schema the package migration merely declines to touch.
#
# `sync` is the honest assertion - it derives ability names from the generated
# resource, creates the permission rows, and creates an Administrator role holding
# them. If the migration did not run, or `grants_all` is missing, or the model is
# not autoloaded, this is where it surfaces.
say "php artisan panel:permissions sync"
php artisan panel:permissions sync --no-interaction 2>&1 | tail -5

# NOT `tinker --execute`. Psy Shell INTERCEPTS `exit()` - it prints "Goodbye" and
# returns its own status - so an exit code threaded through tinker reports nothing
# about the code that ran. The first version of this check did exactly that and
# failed a sync that had plainly worked, which is worse than no check: it accuses
# the product of a fault that is in the harness. A standalone script bootstrapping
# the app is the pattern the route checks already use, and it prints its verdict
# rather than encoding it.
cat > verify-perms.php <<'PERM'
<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

$checks = [
    'grants_all column' => Illuminate\Support\Facades\Schema::hasColumn('roles', 'grants_all'),
    'a role that grants everything' => PanelKit\Panel\Models\Role::query()->where('grants_all', true)->exists(),
    'the generated resource\'s ability' => Spatie\Permission\Models\Permission::query()
        ->where('name', 'view_any_customers')->exists(),
];

foreach ($checks as $what => $ok) {
    echo ($ok ? 'ok   ' : 'MISS '), $what, PHP_EOL;
}

echo in_array(false, $checks, true) ? 'VERDICT fail' : 'VERDICT pass', PHP_EOL;
PERM
perms="$(php verify-perms.php 2>&1)"
rm -f verify-perms.php

echo "$perms"
grep -q 'VERDICT pass' <<<"$perms" \
    || fail "panel:permissions ran but left no working role - the shipped permission system does not work on a clean install."

say "Permissions reconciled: an Administrator role holds the generated resource's abilities"



# A PANEL NEEDS AN APPLICATION THAT CAN AUTHENTICATE. `laravel/laravel` ships
# no auth scaffolding, so there is no `login` route for the guard to send an
# anonymous visitor to - and the first visit dies with "Route [login] not
# defined", which names nothing a newcomer can act on. A real installation has
# Fortify, Breeze or a starter kit; this stands in for one.
say "Adding a login route (standing in for auth scaffolding)"
cat >> routes/web.php <<'ROUTE'

Route::get('/login', fn () => 'login')->name('login');
ROUTE

# THE ASSERTION WORTH MAKING, and it is not a grep of route:list. Panel routes
# use a `{resource}` placeholder constrained by `whereIn`, so no route URI ever
# contains the literal "customers" - an earlier version of this script asserted
# exactly that and reported a bug that did not exist. Resolving the URL is the
# only honest check: 404 means unrouted, 500 means broken, a redirect to login
# means the route matched and the guard ran.
say "Checking the resource URL resolves"
cat > verify-hit.php <<'HIT'
<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
$status = $kernel->handle(Illuminate\Http\Request::create('/customers', 'GET'))->getStatusCode();
echo $status, PHP_EOL;
HIT
status="$(php verify-hit.php 2>/dev/null | tail -1)"
rm -f verify-hit.php

case "$status" in
    404) fail "/customers is not routed - discovery or panel mounting did not happen." ;;
    5*)  fail "/customers is routed but returns $status - the panel errors on a clean install." ;;
    "")  fail "/customers could not be requested at all." ;;
esac

say "/customers resolved with HTTP $status"

# AND THE SCREEN THAT OPERATES IT - CHECKED AFTER THE LOGIN ROUTE EXISTS.
#
# This block sat above that step at first and reported a 500 that had nothing to
# do with roles: an auth-guarded route reached by a guest redirects to
# `route('login')`, and in an app with no auth scaffolding that throws
# `Route [login] not defined`. Which is the very trap documented a few lines up,
# walked into by the check that was added to avoid trusting anything.
# The package mounts the permission matrix by
# default - `panel.routes.roles` - because shipping roles, a model and a
# reconciler while leaving the screen unrouted means a permission system nobody
# can use without writing a controller first. The reference app turns this off
# and mounts its own, so this is the only place the default is exercised.
say "Checking the roles screen is routed"
cat > verify-roles.php <<'HIT'
<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
echo $kernel->handle(Illuminate\Http\Request::create('/roles', 'GET'))->getStatusCode(), PHP_EOL;
HIT
roles_status="$(php verify-roles.php 2>/dev/null | tail -1)"
rm -f verify-roles.php

case "$roles_status" in
    404) fail "/roles is not routed - the package ships a permission matrix nobody can open." ;;
    5*)  fail "/roles is routed but returns $roles_status." ;;
    "")  fail "/roles could not be requested at all." ;;
esac

say "/roles resolved with HTTP $roles_status"

# ---------------------------------------------------------------------------
# TICKETING, WHICH ARRIVES SWITCHED OFF AND MUST STILL ARRIVE.
#
# THIS IS THE ONLY PLACE THE PACKAGED MIGRATION RUNS. Inside the monorepo the
# reference app built `tickets` / `ticket_replies` long before the package owned
# them and config points at those, so the migration this ships takes the branch
# where the table already exists - in every one of the 1,596 tests. A fresh app
# is the first database it has ever actually created a table in.
#
# AND OFF IS A REAL STATE, not an absence. With neither panel named, nothing
# mounts: no route, no navigation entry, no screen. That is the correct posture
# for an installation that did not ask for a support desk, and it is also
# indistinguishable from a plugin that silently failed to register - so both
# halves are checked here rather than one.
# ---------------------------------------------------------------------------
say "Checking the ticket tables were created"
cat > verify-tickets.php <<'TIX'
<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use Illuminate\Support\Facades\Schema;

$checks = [
    'panel_tickets' => Schema::hasTable('panel_tickets'),
    'panel_ticket_replies' => Schema::hasTable('panel_ticket_replies'),
    'the reply thread has a body' => Schema::hasColumn('panel_ticket_replies', 'body'),
    'an internal note is distinguishable' => Schema::hasColumn('panel_ticket_replies', 'visibility'),
    'the first-response clock has somewhere to live' => Schema::hasColumn('panel_tickets', 'first_response_at'),
    'nothing mounted, because no panel was named'
        => ! array_key_exists('tickets', app(PanelKit\Panel\PanelManager::class)->resources()),
];

foreach ($checks as $what => $ok) {
    echo ($ok ? 'ok   ' : 'MISS '), $what, PHP_EOL;
}

echo in_array(false, $checks, true) ? 'VERDICT fail' : 'VERDICT pass', PHP_EOL;
TIX
tickets="$(php verify-tickets.php 2>&1)"
rm -f verify-tickets.php

echo "$tickets"
grep -q 'VERDICT pass' <<<"$tickets" \
    || fail "the packaged ticketing migration did not produce a usable schema on a clean install."

# NOW TURN IT ON, which is the half that matters: the tables are worth nothing
# if naming a panel does not produce a screen. `PANEL_TICKETING_OPERATOR` is
# read by the published config, so this is the same edit a consumer makes.
say "Turning ticketing on and checking the queue routes"
printf '\nPANEL_TICKETING_OPERATOR=%s\n' "$(php -r '
require __DIR__."/vendor/autoload.php";
$app = require_once __DIR__."/bootstrap/app.php";
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
echo array_key_first(app(PanelKit\Panel\PanelManager::class)->all());
')" >> .env

php artisan config:clear >/dev/null 2>&1 || true

cat > verify-queue.php <<'HIT'
<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
echo $kernel->handle(Illuminate\Http\Request::create('/tickets', 'GET'))->getStatusCode(), PHP_EOL;
HIT
tickets_status="$(php verify-queue.php 2>/dev/null | tail -1)"
rm -f verify-queue.php

case "$tickets_status" in
    404) fail "ticketing was configured and /tickets is still unrouted - the plugin did not mount." ;;
    5*)  fail "/tickets is routed but returns $tickets_status on a clean install." ;;
    "")  fail "/tickets could not be requested at all." ;;
esac

say "/tickets resolved with HTTP $tickets_status"

# ---------------------------------------------------------------------------
# THE UPGRADE PATH, on the only kind of installation that can prove it.
#
# Everything above verifies `composer require`. `panel:update` is what somebody
# runs AFTER that, on every release from then on - and it is the command with
# the most to touch: it writes page files, invalidates the schema cache, reads
# the application's published `config/panel.php` and ends by running doctor.
#
# NONE OF THAT CAN BE TRUSTED FROM INSIDE THE MONOREPO, for the same reason the
# rest of this script exists: there the package is a symlink and the config is
# the playground's, edited by hand over months. A fresh application is the only
# place where "the published config matches the package" is a fact rather than
# an accident, so it is the only place a drift report can be checked against a
# known answer.
#
# ITS EXIT CODE IS DOCTOR'S, and this fixture FAILS doctor on purpose. A bare
# `laravel/laravel` publishes Spatie's config with `teams => false` while the
# panel's tenancy mode defaults to `column`, which is fail-open - a role would
# grant across every organisation at once - so doctor errors and `panel:update`
# returns non-zero. That is the design working, not a break, and asserting a
# zero here would mean asserting that doctor stays quiet about it.
#
# So the exit code is CAPTURED rather than trusted, and what is checked is what
# each step reported.
# ---------------------------------------------------------------------------
say "php artisan panel:update"

update_output="$(php artisan panel:update 2>&1)" && update_status=0 || update_status=$?

# A BARE LARAVEL IS NOT AN INERTIA APPLICATION, so there is no
# `resources/js/pages` to write into and the command has to say so rather than
# claim success. Whichever answer it gives, it must be about the page files -
# silence there is the failure this command exists to prevent.
case "$update_output" in
    *"page files already complete"*|*"no resources/js/pages directory"*) ;;
    *) fail "panel:update said nothing about page files, which is the reason it exists:
$update_output" ;;
esac

case "$update_output" in
    *"invalidated the schema cache"*) ;;
    *) fail "panel:update did not invalidate the schema cache - an upgrade would serve the old schema shape:
$update_output" ;;
esac

# A config published minutes ago by `panel:install` cannot be missing a key.
# Anything reported here is the CHECK being wrong, not the installation.
case "$update_output" in
    *"config key(s) missing"*) fail "panel:update reports config drift against a config it just published, so the check is wrong:
$update_output" ;;
esac

# AND THE EXIT CODE IS DOCTOR'S. Non-zero is expected here, for the fail-open
# permission config a bare Laravel ships; what would be wrong is doctor passing
# a fixture nobody configured, which would mean it had stopped looking.
if [ "$update_status" -eq 0 ]; then
    fail "panel:update exited zero on an unconfigured install - doctor should have refused a fail-open permission config."
fi

case "$update_output" in
    *"Permissions are not tenant-scoped"*) ;;
    *) fail "panel:update exited $update_status for a reason other than the expected permission-scoping error:
$update_output" ;;
esac

say "panel:update reconciles what it should, and carries doctor's non-zero verdict on an unconfigured install"

echo
echo "PASS - panelkit/panel installs into a fresh Laravel app, is discovered,"
echo "       installs its pages, generates a resource, routes it, and survives"
echo "       panel:update."
