<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Roles, and what each one is allowed to do.
 *
 * WHY A JSON COLUMN RATHER THAN A PERMISSIONS TABLE AND TWO PIVOTS. The
 * permission names are not data - they are DERIVED from the registered
 * resources, regenerated by `panel:permissions sync`, and meaningless without
 * the resource they name. A `permissions` table would be a second copy of the
 * registry that can fall out of step with it, plus a pivot whose only job is to
 * answer a question one array membership test answers.
 *
 * The cost of the JSON column is that you cannot ask "which roles grant
 * update_client" in SQL. That query has one caller - the matrix screen - which
 * loads every role for the tenant anyway, because it is rendering all of them.
 *
 * ROLES ARE TENANT DATA. An "Administrator" at one ISP has nothing to do with an
 * "Administrator" at another, and a role shared between tenants is a privilege
 * escalation path: edit the role at your own organisation, gain the ability at
 * somebody else's. Hence tenant_id, and the unique index that scopes the slug to
 * it rather than making it globally unique.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('roles', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('tenant_id')->constrained()->cascadeOnDelete();

            $table->string('name');
            $table->string('slug');
            $table->json('permissions')->default('[]');

            /*
             * The role new users get. Nullable-by-absence rather than a
             * separate table: exactly one role per tenant should carry it, and
             * that is enforced in the application rather than by a partial
             * index, which SQLite and MySQL express differently.
             */
            $table->boolean('is_default')->default(false);

            $table->timestamps();

            $table->unique(['tenant_id', 'slug']);
        });

        Schema::table('users', function (Blueprint $table): void {
            /*
             * NULLABLE, and null means NO PERMISSIONS - not "all of them".
             *
             * This is the same deny-by-default posture the panel takes when a
             * policy is missing, and it is the choice that makes a forgotten
             * assignment lock somebody out rather than quietly hand them
             * everything. `panel:permissions sync` is what fills it in.
             */
            $table->foreignId('role_id')->nullable()->after('tenant_id')->constrained()->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('users', function (Blueprint $table): void {
            $table->dropConstrainedForeignId('role_id');
        });

        Schema::dropIfExists('roles');
    }
};
